#
# Erp System - Jehoiada Series
# Copyright Â© 2021 - 2023 Edwin Njeru (mailnjeru@gmail.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

# This configuration is intended for development purpose, it's **your** responsibility to harden it for production

version: '3.3'

networks:
  erp-system-network:
    driver: bridge

services:
  # erpsystem-postgresql:
  #   image: postgres:13.4
  #   volumes:
  #     - ./postgresql-data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_USER=${PG_DATABASE_DEV_USER}
  #     - POSTGRES_PASSWORD=${PG_DATABASE_PROD_PASSWORD}
  #     - POSTGRES_DB=erpSystem
  #     - POSTGRES_HOST_AUTH_METHOD=trust
  #   ports:
  #     - 5532:5432
  #   networks:
  #     - erp-system-network
      
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
  #     - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
  #   ports:
  #     - 8982:80
  #   depends_on:
  #     - erpsystem-postgresql
  #   networks:
  #     - erp-system-network

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.5
    volumes:
      - ./zookeeper-data:/var/lib/zookeeper/data
      - ./zookeeper-logs:/var/lib/zookeeper/log
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - erp-system-network

  kafka:
    image: confluentinc/cp-kafka:5.5.5
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_INTERNAL:PLAINTEXT,DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: DOCKER_INTERNAL://:29092,DOCKER_EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: DOCKER_INTERNAL://kafka:29092,DOCKER_EXTERNAL://${DOCKER_HOST_IP:-localhost}:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    volumes:
      - ./kafka-queue:/var/lib/kafka/data
    networks:
      - erp-system-network

  jhipster-registry:
    image: jhipster/jhipster-registry:v7.3.0
    volumes:
      - ./central-server-config:/central-config
    # When run with the "dev" Spring profile, the JHipster Registry will
    # read the config from the local filesystem (central-server-config directory)
    # When run with the "prod" Spring profile, it will read the configuration from a Git repository
    # See https://www.jhipster.tech/jhipster-registry/#spring-cloud-config
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,api-docs
      - SPRING_SECURITY_USER_PASSWORD=admin
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/localhost-config/
      # - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=git
      # - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_URI=https://github.com/jhipster/jhipster-registry/
      # - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_PATHS=central-config
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 8761:8761
    networks:
      - erp-system-network

  erpsystem-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    volumes:
      - ./search-index-directory:/usr/share/elasticsearch/data
    ports:
      #- 127.0.0.1:9200:9200
      - 9200:9200
      #- 127.0.0.1:9300:9300
      - 9300:9300
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - "cluster.max_shards_per_node=3000"
      # - "index.mapping.total_fields.limit=2000"
    networks:
      - erp-system-network

  erp-system-server:
    image: ghacupha/erp-system:1.8.3
    volumes:
      - ./logs/:/logs/
      - ./reports-directory/:/reports-directory/
      - ./generated-reports/:/generated-reports/
      - ./business-documents/:/business-documents/
    environment:
      - _JAVA_OPTIONS=-Xmx4096m -XX:MaxRAMPercentage=50.0 -XX:MinRAMPercentage=80.0 -XX:InitialRAMPercentage=50.0 -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:admin@jhipster-registry:8761/eureka
      #- EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
      - SPRING_CLOUD_CONFIG_URI=http://admin:admin@jhipster-registry:8761/config
      #- SPRING_DATASOURCE_URL=jdbc:postgresql://erpsystem-postgresql:5432/erpSystem
      #- SPRING_LIQUIBASE_URL=jdbc:postgresql://erpsystem-postgresql:5432/erpSystem
      - SPRING_DATASOURCE_URL=${LOCAL_PG_SERVER}/${ERP_SYSTEM_PROD_DB}
      - SPRING_LIQUIBASE_URL=${LOCAL_PG_SERVER}/${ERP_SYSTEM_PROD_DB}
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:29092
      - KAFKA_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_REPLICATION_FACTOR=8
      - SPRING_ELASTICSEARCH_REST_URIS=http://erpsystem-elasticsearch:9200
      #- SPRING_ELASTICSEARCH_REST_URIS=${SPRING_DATA_JEST_URI}
      - ERP_SYSTEM_PROD_DB=${ERP_SYSTEM_PROD_DB}
      - ERP_SYSTEM_DEV_DB=${ERP_SYSTEM_DEV_DB}
      - ERP_SYSTEM_PORT=${ERP_SYSTEM_PORT}
      - PG_DATABASE_DEV_USER=${PG_DATABASE_DEV_USER}
      - PG_DATABASE_PROD_USER=${PG_DATABASE_PROD_USER}
      - PG_DATABASE_DEV_PASSWORD=${PG_DATABASE_DEV_PASSWORD}
      - PG_DATABASE_PROD_PASSWORD=${PG_DATABASE_PROD_PASSWORD}
      - LOCAL_PG_SERVER=${LOCAL_PG_SERVER}
      - ERP_SYSTEM_DEV_PORT=${ERP_SYSTEM_DEV_PORT}
      - ERP_SYSTEM_PROD_PORT=${ERP_SYSTEM_PROD_PORT}
      - ERP_SYSTEM_PROD_MAIL_BASE_URL=${ERP_SYSTEM_PROD_MAIL_BASE_URL}
      - ERP_SYSTEM_DEV_MAIL_BASE_URL=${ERP_SYSTEM_DEV_MAIL_BASE_URL}
      - SECURITY_AUTHENTICATION_JWT_BASE64_SECRET=${SECURITY_AUTHENTICATION_JWT_BASE64_SECRET}
      - UPLOADS_SIZE=${UPLOADS_SIZE}
      - SANDBOX_INSTANCE_URLS=${SANDBOX_INSTANCE_URLS}
      - ERP_REINDEXER_INTERVAL=${ERP_REINDEXER_INTERVAL}
      - ERP_REINDEXER_INTERVAL_DEV=${ERP_REINDEXER_INTERVAL_DEV}
      - ERP_REINDEXER_INTERVAL_PROD=${ERP_REINDEXER_INTERVAL_PROD}
      - ERP_DOCUMENTS_MAX_FILE_SIZE=${ERP_DOCUMENTS_MAX_FILE_SIZE}
      - ERP_INDEX_ENABLED=${ERP_INDEX_ENABLED}
      - ERP_INDEX_REBUILD_ENABLED=${ERP_INDEX_REBUILD_ENABLED}
      - ERP_SYSTEM_EMAIL_USER=${ERP_SYSTEM_EMAIL_USER}
      - ERP_SYSTEM_EMAIL_PASSWORD=${ERP_SYSTEM_EMAIL_PASSWORD}
      - ERP_CACHE_REBUILD_ENABLED=${ERP_CACHE_REBUILD_ENABLED}
      - ERP_CACHE_TEARDOWN_REBUILD_ENABLED=${ERP_CACHE_TEARDOWN_REBUILD_ENABLED}
    ports:
      #- 8980:8980
      - ${ERP_SERVER_DEPLOYMENT_PROD_PORT}
    networks:
      - erp-system-network
    depends_on:
      - kafka

  erp-client-web:
    image: ghacupha/erp-client:1.7.9
    environment:
      - SERVER_API_URL=${SERVER_API_URL}
      - SERVER_API_URL_URL=${SERVER_API_URL_URL}
      - SERVER_API_WS_URL=${SERVER_API_WS_URL}
      - ERP_SYSTEM_DEV_PORT=${ERP_SYSTEM_DEV_PORT}
      - ERP_CLIENT_DEV_PORT=${ERP_CLIENT_DEV_PORT}
      - SERVER_API_DOCKER_DEPLOY_HOST=http://erp-system-server
    ports:
      #- "8981:80"
      - ${ERP_CLIENT_DEPLOYMENT_PROD_PORT}
    networks:
      - erp-system-network

  # gdi-staging:
  #   image: ghacupha/gdi-staging:0.0.1-SNAPSHOT
  #   environment:
  #     - SERVER_NAME=erp-system-server
  #     - SERVER_API_DOCKER_DEPLOY_HOST=erp-system-server
  #     - SERVER_API_DOCKER_DEPLOY_PORT=8980
  #     - SERVER_API_URL=erp-system-server:8980/
  #     - GDI_CLIENT_DEV_PORT=${GDI_CLIENT_DEV_PORT}
  #     - ERP_DOCUMENTS_MAX_FILE_SIZE=${ERP_DOCUMENTS_MAX_FILE_SIZE}
  #     - CLIENT_MAX_FILE_SIZE=${CLIENT_MAX_FILE_SIZE}
  #   ports:
  #     - "8983:80"
  #     #- ${GDI_CLIENT_DEPLOYMENT_PROD_PORT}
  #   networks:
  #     - erp-system-network


  # ng-gdi-staging:
  #   image: ghacupha/ng-gdi-staging-794:0.0.1-SNAPSHOT
  #   environment:
  #     - SERVER_API_URL="http://erp-system-server:${SERVER_API_DOCKER_DEPLOY_PORT}/"
  #     - SERVER_API_URL_URL=http://erp-system-server
  #     - ERP_SYSTEM_DEV_PORT=${ERP_SYSTEM_DEV_PORT}
  #     - ERP_CLIENT_DEV_PORT=${ERP_CLIENT_DEV_PORT}
  #     - SERVER_API_DOCKER_DEPLOY_HOST=http://erp-system-server
  #     - SERVER_API_DOCKER_DEPLOY_PORT=${SERVER_API_DOCKER_DEPLOY_PORT}
  #   ports:
  #     - "8987:80"
  #   networks:
  #     - erp-system-network

  # erp-client-ng-prep-web:
  #   image: ghacupha/erp-client-ng-prep:0.0.2-SNAPSHOT
  #   environment:
  #     - SERVER_API_URL=${SERVER_API_URL}
  #     - SERVER_API_URL_URL=${SERVER_API_URL_URL}
  #     - SERVER_API_WS_URL=${SERVER_API_WS_URL}
  #     - ERP_SYSTEM_DEV_PORT=${ERP_SYSTEM_DEV_PORT}
  #     - ERP_CLIENT_NG_PREP_DEV_PORT=8986
  #     - SERVER_API_DOCKER_DEPLOY_HOST=http://erp-system-server
  #   ports:
  #     - "8986:80"
  #   networks:
  #     - erp-system-network