name: Application CI
on: [push, pull_request]
jobs:
    pipeline:
        name: ERP Client pipeline
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
        timeout-minutes: 40
        env:
            NODE_VERSION: 12.16.1
            JHI_DISABLE_WEBPACK_LOGS: true
            NG_CLI_ANALYTICS: false
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.16.1

            - name: Install node.js packages
              working-directory: ./erp-client
              run: npm install

            - name: Run frontend test
              working-directory: ./erp-client
              run: npm run test

            - name: Package application
              working-directory: ./erp-client
              run: npm run build

            - name: Login to Docker hub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build docker image
              working-directory: ./erp-client
              run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_ORG }}/${{ secrets.DOCKERHUB_REPO }}:${{ secrets.DOCKERHUB_VER }}

            - name: Push docker image
              working-directory: ./erp-client
              run: docker push ${{ secrets.DOCKERHUB_ORG }}/${{ secrets.DOCKERHUB_REPO }}:${{ secrets.DOCKERHUB_VER }}
